const expense = [
  {"expenseCode": "ACI", "chineseName": "ACI 反恐申报费", "englishName": "ACI FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "AFR", "chineseName": "AFR反恐申报费", "englishName": "AFR FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "AFS", "chineseName": "AFS申报附加费", "englishName": "ADVANCE FILING SURCHARGE", "defaultBillingMethod": "票", "defaultCurrency": "USD","invoiceTaxRate": 4},
  {"expenseCode": "AMETF", "chineseName": "提单更改费", "englishName": "AMENDMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CAF", "chineseName": "币值附加费", "englishName": "CURRENCY ADJUSTMENT FACTOR", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "AGNTF", "chineseName": "代理费", "englishName": "AGENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "CEXF", "chineseName": "货运快递费", "englishName": "EXPRESS FEE OF CARGO", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "CHASR", "chineseName": "车架租赁费", "englishName": "CHASSIS RENTAL", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CHASSIS", "chineseName": "托架费", "englishName": "CHASSIS FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CIS", "chineseName": "平衡费", "englishName": "CONTAINER IMBALANCE SURCHARGE (CIS)", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CORF", "chineseName": "修箱费", "englishName": "CONTANIER REPAIR FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "COVWF", "chineseName": "集装箱超重费", "englishName": "CONTAINER OVERWEIGHT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CPPF", "chineseName": "报关预录平台使用费", "englishName": "CUSTOMS PRE-RECORDED PLATFORM USAGE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CTDTF", "chineseName": "洗箱费", "englishName": "CONTAINER DIRTYNESS CHANGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CTQTF", "chineseName": "箱体检疫费", "englishName": "CONTANIER QUARANTINE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "CUSDSB", "chineseName": "海关代收代付费用", "englishName": "CUSTOMS COLLECTS AND PAYS", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "DACS", "chineseName": "危险品附加费", "englishName": "DANGEROUS CARGO SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DBILL", "chineseName": "目的港 B/L 提单放单费", "englishName": "DESTINATION BILLING FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "DCART", "chineseName": "目的港送货费", "englishName": "DELIVERY CHARGE AT PORT OF DESTINATION", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "DDDGF", "chineseName": "目的港危险品费", "englishName": "DECLARATION FEE FOR DANGEROUS GOODS AT DESTINATION PORT", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DDOC", "chineseName": "目的港文件费", "englishName": "DESTINATION PORT OF DOCUMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "DECHF", "chineseName": "改港费", "englishName": "CHANGE OF DESTINATION PORT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DEHC", "chineseName": "目的港设备交接费（LoLo）", "englishName": "LIFT ON LIFT OFF AT DESTINATION PORT", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DEXF", "chineseName": "文件快递费", "englishName": "EXPRESS FEE OF DOCUMENT", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "DFSC", "chineseName": "送货燃油附加费", "englishName": "FUEL SURCHARGE IN DELIVERY", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DFUMI", "chineseName": "目的港熏蒸费", "englishName": "DESTINATION FUMIGATION FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DISF", "chineseName": "消毒费", "englishName": "DISINFECTION FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DNOTE", "chineseName": "目的港其他费用", "englishName": "OTHER CHARGE IN THE DESTINATION PORT", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "DPCH", "chineseName": "目的港费用all in", "englishName": "DESTINATION ALL IN", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "DPOF", "chineseName": "落箱费", "englishName": "DROP-OFF FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DQUAR", "chineseName": "目的港检验检疫费", "englishName": "DESTINATION PORT INSPECTION AND QUARANTINE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DRFF", "chineseName": "目的港退回费", "englishName": "POD REFUND FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DSEC", "chineseName": "目的港安全附加费", "englishName": "DESTINATION PORT SECURITY CHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DSTOR", "chineseName": "目的港仓储费", "englishName": "WAREHOUSE STORAGE IN THE PORT OF DESTINATION", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DTHC", "chineseName": "目的港码头操作费", "englishName": "DESTINATION TERMINAL HANDLING CHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DTSE", "chineseName": "目的港转关费", "englishName": "DESTINATION TRANSIT FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "DWHARF", "chineseName": "目的港码头附加费", "englishName": "SURCHARGE OF DESTINATION WHARF", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "ECC", "chineseName": "出口报关费", "englishName": "EXPORT CUSTOMS CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OCCLR", "chineseName": "进口海关清关费", "englishName": "IMPORT CUSTOM CLEARANCE CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "EDETS", "chineseName": "起运港集装箱滞箱费", "englishName": "ORIGINAL PORT OF DEMURRAGE & DETENTION", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "EDIMF", "chineseName": "舱单费", "englishName": "MANIFEST FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "ENPA", "chineseName": "预进港", "englishName": "ENTER THE PORT IN ADVANCE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "ENS", "chineseName": "ENS 反恐申报费", "englishName": "ENS FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "FDAF", "chineseName": "美国食品和药物管理局申报费(FDA)", "englishName": "FOOD AND DRUG ADMINISTRATION FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "FDVC", "chineseName": "支线费", "englishName": "FEEDER VESSEL CHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "IDETS", "chineseName": "目的港集装箱滞箱费", "englishName": "DESTINATION PORT OF DEMURRAGE&DETENTION", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "ISF", "chineseName": "ISF 申报费", "englishName": "ISF FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "LRFF", "chineseName": "起运港退舱费", "englishName": "POL REFUND FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "LSS", "chineseName": "低硫费", "englishName": "LOW SULPHUR SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "NOSHF", "chineseName": "亏舱费", "englishName": "NO SHOW FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "OADOC", "chineseName": "运抵费", "englishName": "ORIGIN ARRIVE DOCUMENT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OCART", "chineseName": "起运港提货费", "englishName": "PICKUP CHARGE AT PORT OF ORIGIN", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OCDF", "chineseName": "综合单证费", "englishName": "ORIGIN COMPREHENSIVE DOCUMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OTESUR", "chineseName": "场站费", "englishName": "TERMINAL SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OCSF", "chineseName": "铅封费", "englishName": "ORIGIN CONTAINER SEAL FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "ODOC", "chineseName": "起运港文件费", "englishName": "ORIGIONAL PORT OF DOCUMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OEDI", "chineseName": "海关数据传输服务费", "englishName": "ELECTRONIC DATA INTERCHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OEHC", "chineseName": "起运港设备交接费（LoLo）", "englishName": "LIFT ON LIFT OFF AT ORIGIN PORT", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OEIR", "chineseName": "集装箱设备交接单", "englishName": "EQUIPMENT INTERCHANGE RECEIPT", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OEMF", "chineseName": "设备管理费", "englishName": "ORIGIN EQUIPMENT MANAGEMENT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OESF", "chineseName": "出口服务费", "englishName": "ORIGIN EXPROT SERVICE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OFUMI", "chineseName": "起运港熏蒸费", "englishName": "ORIGIN FUMIGATION FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OISPS", "chineseName": "船公司安保费", "englishName": "INTERNATIONAL SHIP AND PORT FACILITY SECURITY  FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "ONOTE", "chineseName": "起运港其他费用", "englishName": "OTHER CHARGE IN THE ORIGIN PORT", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OPBD", "chineseName": "预录费", "englishName": "PRERECORD FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OPCH", "chineseName": "起运港费用  all in", "englishName": "ORIGIN ALL IN", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OPMDOC", "chineseName": "预配舱单录入费", "englishName": "ORIGIN PRE MANIFEST DOCUMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OPSUR", "chineseName": "港口附加费", "englishName": "PORT SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "OQUAR", "chineseName": "起运港检验检疫费", "englishName": "ORIGIN PORT INSPECTION AND QUARANTINE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OSEC", "chineseName": "起运港安全附加费", "englishName": "ORIGIN PORT SECURITY CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OSTOR", "chineseName": "起运港仓储费", "englishName": "WAREHOUSE STORAGE IN THE PORT OF ORIGIN", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OTHC", "chineseName": "起运港码头操作费", "englishName": "ORIGIN TERMINAL HANDLING CHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OTSE", "chineseName": "起运港转关费", "englishName": "ORIGIN TRANSIT FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OVTF", "chineseName": "加班费", "englishName": "OVERTIME PAY", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "PALTC", "chineseName": "托盘耗材费", "englishName": "PALLET FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "PCS", "chineseName": "港口拥堵费", "englishName": "UKS SURCHARGE PROT", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "PKADF", "chineseName": "预提费", "englishName": "PICK UP IN ADVANCE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "PKLF", "chineseName": "箱单费", "englishName": "PACKING LIST FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "PRCF", "chineseName": "预冷费", "englishName": "PRECOOL FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "PRFF", "chineseName": "压车费", "englishName": "PRESS FARE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "PRKF", "chineseName": "停车费", "englishName": "PARKING FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "RELOF", "chineseName": "改配移箱费", "englishName": "RELOCATION FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "RETNF", "chineseName": "还箱费", "englishName": "CONTANIER RETURN FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "RINF", "chineseName": "加固费", "englishName": "REINFORCE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "RODF", "chineseName": "拖车运费-FCL", "englishName": "RODF", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "SAINS", "chineseName": "动卫检费", "englishName": "SANITARY INSPECTION", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "SPLCF", "chineseName": "船证明", "englishName": "SHIP LICENSE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "STRTF", "chineseName": "集装箱短租费", "englishName": "SHORT-TERM RENTAL FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TAXF", "chineseName": "关税", "englishName": "DUTY", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "TFRT", "chineseName": "铁路运费", "englishName": "TRAIN FREIGHT", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TKVTF", "chineseName": "放空费", "englishName": "VENT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TKWTF", "chineseName": "卡车等待费", "englishName": "WAITING TIME FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TLYF", "chineseName": "点货理货费", "englishName": "TALLY FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TOVWF", "chineseName": "卡车超重费", "englishName": "TRUCK OVERWEIGHT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "VGM", "chineseName": "VGM申报费", "englishName": "VERIFIED GROSS MASS", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "WAR", "chineseName": "战争风险附加费", "englishName": "WAR SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "WEIGF", "chineseName": "过磅费", "englishName": "WEIGHING FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "WLUF", "chineseName": "仓库装卸货费", "englishName": "WAREHOUSE LOADING AND UNLOADING FEES", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CHGOV", "chineseName": "改船费", "englishName": "CHANGE OF VESSEL", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CBBKF", "chineseName": "合并提单费", "englishName": "COMBINATION OF BOOKING FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CNSLF", "chineseName": "拼箱费", "englishName": "CONSOLATION FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OPSTG", "chineseName": "起运港堆存费", "englishName": "ORIGIN PORT STORAGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "DPSTG", "chineseName": "目的港堆存费", "englishName": "DESTINATION PORT STORAGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "OPDMG", "chineseName": "起运港滞箱费", "englishName": "ORIGIN PORT DEMURRAGE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "DPDMG", "chineseName": "目的港滞箱费", "englishName": "DESTINATION PORT DEMURRAGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "ELPAKL", "chineseName": "装箱信息费", "englishName": "ELECTRONIC PACKING LIST", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "PKTEN", "chineseName": "场站提箱操作费", "englishName": "PICK UP IN TERMINAL", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "LODC", "chineseName": "排载费", "englishName": "LOADING COST", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "WARHSIF", "chineseName": "搬仓费", "englishName": "WAREHOUSING FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CHWAEL", "chineseName": "水电费", "englishName": "CHARGES FOR WATER AND ELECTRICITY", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "GATCG", "chineseName": "闸口费", "englishName": "GATE CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OVNICG", "chineseName": "压夜费", "englishName": "OVER NIGHT CHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "CNRTNF", "chineseName": "集装箱调空费", "englishName": "CONTAINER RETURN FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "CASF", "chineseName": "挑箱费", "englishName": "CASE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "DEVNCG", "chineseName": "掏箱费", "englishName": "DEVANNING CHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TNNTO", "chineseName": "隧道费", "englishName": "TUNNEL TOLL", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "HADF", "chineseName": "操作附加费", "englishName": "HANDLING FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "AAF", "chineseName": "反恐申报信息更改费", "englishName": "AMS/ENS/ACI/AFR AMENDMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "LDSS", "chineseName": "监装费", "englishName": "LOADING SUPERVISION SURCHARGE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "CW1UC", "chineseName": "CW1未知费用项", "englishName": "CW1 UNKNOWN CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "AMS", "chineseName": "AMS反恐申报费", "englishName": "AMS FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "BAF", "chineseName": "燃油附加费", "englishName": "BUNKER ADJUSTMENT FACTOR", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "LC1", "chineseName": "包干费", "englishName": "LOCAL CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CCF1", "chineseName": "报关费", "englishName": "CUSTOMS CLEARANCE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "IC", "chineseName": "保险费", "englishName": "INSURANCE CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "SF", "chineseName": "仓储费", "englishName": "STORAGE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "UPKF", "chineseName": "拆箱费", "englishName": "UNPACKING FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OBOF", "chineseName": "订舱费", "englishName": "BOOKING FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "TLRF", "chineseName": "电放费", "englishName": "TELEX RELEASE FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "EFAF", "chineseName": "紧急燃油附加费", "englishName": "EMERGENT FUEL ANDJUSTMENT FACTOR", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "DC2", "chineseName": "分拨费", "englishName": "DISPATCH CHARGE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CHAF", "chineseName": "换单费", "englishName": "DOCUMENT EXCHANGE FEE", "defaultBillingMethod": "票", "defaultCurrency": "USD"},
  {"expenseCode": "CUIPF", "chineseName": "海关查验费", "englishName": "CUSTOMS INSPECTION FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OFRT", "chineseName": "海运费", "englishName": "OCEAN FREIGHT", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "PSS", "chineseName": "旺季附加费", "englishName": "PEAK SEASON SRUCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "INSPF", "chineseName": "商检费", "englishName": "COMMODITY INSPECTION FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "ISTDF", "chineseName": "商检换单费", "englishName": "COMMODITY INSPECTION DOUCUMENT TRANSFER FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "WARS", "chineseName": "战争附加费", "englishName": "WAR SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  // sp11 新增
  {"expenseCode": "AADOC", "chineseName": "改运抵费", "englishName": "AMEND ARRIVE DOCUMENT FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "FLSF", "chineseName": "燃油及土地附加费", "englishName": "FUEL AND LAND SURCHARGE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "EDIMDF", "chineseName": "舱单删除费", "englishName": "MANIFEST DELET FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "CISF", "chineseName": "海关查验服务费", "englishName": "LOADING AND UNLOADING TRANSLATION FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "LUTF", "chineseName": "装卸平移费", "englishName": "LOADING AND UNLOADING TRANSLATION FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "WSCF", "chineseName": "仓储包干费", "englishName": "WAREHOUSE STORAGE COVER FEE", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "OCTAF", "chineseName": "指号费", "englishName": "CONTAINER APPOINT FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OCPSF", "chineseName": "综合服务费", "englishName": "COMPREHENSIVE SERVICE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OPSF", "chineseName": "港务费", "englishName": "PORT SERVICE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "OPLF", "chineseName": "港杂费", "englishName": "PORT LOCAL FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY"},
  {"expenseCode": "CTUF", "chineseName": "集装箱使用费", "englishName": "CONTAINER USAGE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "ARB", "chineseName": "驳船费", "englishName": "ARBITRARY AT LOAD", "defaultBillingMethod": "箱", "defaultCurrency": "USD"},
  {"expenseCode": "CQF", "chineseName": "柜检费", "englishName": "CONTAINER QUARANTINE FEE", "defaultBillingMethod": "箱", "defaultCurrency": "CNY", "invoiceTaxRate": 4},
  {"expenseCode": "PIPA", "chineseName": "疏港费", "englishName": "PIER PASS", "defaultBillingMethod": "票", "defaultCurrency": "USD", "invoiceTaxRate": 4},
  {"expenseCode": "CHSP", "chineseName": "底盘分离费", "englishName": "CHASSIS SPLIT", "defaultBillingMethod": "票", "defaultCurrency": "USD", "invoiceTaxRate": 4},
  {"expenseCode": "PRPU", "chineseName": "预拉费", "englishName": "PRE PULL", "defaultBillingMethod": "票", "defaultCurrency": "USD", "invoiceTaxRate": 4},
  {"expenseCode": "PLW", "chineseName": "巴拿马低水位附加费", "englishName": "PANAMA CANAL LOW WATER SURCHARGE", "defaultBillingMethod": "箱", "defaultCurrency": "USD", "invoiceTaxRate": 4},
  {"expenseCode": "YAS", "chineseName": "YAS 日元升值费", "englishName": "YEN APPRECIATION", "defaultBillingMethod": "箱", "defaultCurrency": "USD", "invoiceTaxRate": 4},
  {"expenseCode": "PRS", "chineseName": "PRS 利润分成", "englishName": "PROFIT SHARE", "defaultBillingMethod": "票", "defaultCurrency": "USD", "invoiceTaxRate": 4},
  // sp20 新增
  {"expenseCode": "LABF", "chineseName": "贴唛费", "englishName": "Labeling Fee", "defaultBillingMethod": "件", "defaultCurrency": "CNY"},
  {"expenseCode": "WHRF", "chineseName": "仓库租金", "englishName": "Warehouse Renting fee", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "DIF", "chineseName": "拆托", "englishName": "Dismantling Fee", "defaultBillingMethod": "件", "defaultCurrency": "CNY"},
  {"expenseCode": "RESTF", "chineseName": "掏箱重装", "englishName": "Restuffing Fee", "defaultBillingMethod": "票", "defaultCurrency": "CNY"},
  {"expenseCode": "WHF", "chineseName": "仓库操作费", "englishName": "Warehouse Handling Fee", "defaultBillingMethod": "每立方米", "defaultCurrency": "CNY"},

]
export default expense
