const userReferenceTypeOptions = [ // 用户参考类型
  'AES Number',
  'AQSIQ',
  'B/L Reference Number',
  'BK Sales ID',
  'Bill Of Entry Date',
  'Bill Of Entry Number',
  'Carcommit Due Date',
  'Carcommit Due Number',
  'Charge quoted by SA',
  'Collect Date',
  'Contract Number',
  'Customer Reference Number',
  'Customer Site ID',
  'Customs Status Information',
  'Declarant CR Number',
  'Demurrage Collected',
  'Department Number',
  'Door date',
  'EEI---Electronic Export Information',
  'Egypt ACID Number',
  'Egypt Exporter Registration Number',
  'Egypt Importer VAT Number',
  'Electronic Custom Clearance Number (AUS)',
  'Empty P/U Location',
  'FEIN number (for shipper)',
  'First Carrier B/L Number (HKG)',
  'Forwarder Reference',
  'HK RO NO',
  'Hot Delivery Service',
  'House B/L',
  'Inbound Customer Reference',
  'Invoice Number',
  'Letter of Credit',
  'Master Booking Number',
  'Merchant haulage vendor',
  'Pattern Booking Number',
  'Pre Booking Number',
  'Proof of Report for ACI',
  'Purchase Order Number',
  'Quotation Number',
  'Reference Of Item',
  'ReleaseDate',
  'Repetitive Pattern Code',
  'Reserved (Inbound Split B/L)',
  'Reserved (Memo B/L)',
  'S/O Number',
  'SC Commodity Group',
  'SCAC code',
  'Shipper Reference',
  'Shippers Identity For Shipment (SID)',
  'Shipping Instruction Reference',
  'Storage Paid Until',
  'T/S Agreement for US',
  'Time Volume Rate',
  'VAT number (for consignee)',
  'VGM Reference Number',
  'Warranty Registration Number',
  'XTN---External Transaction Number'
]
export default userReferenceTypeOptions
