const searchData = [{
  "itemType": "date",
  "subType": "daterange",
  "itemName": "etd",
  "itemLabel": "开航日期",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "date",
  "subType": "daterange",
  "itemName": "createTime",
  "itemLabel": "创建日期",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "date",
  "subType": "daterange",
  "itemName": "closeCustomsDate",
  "itemLabel": "截关日期",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "customer",
  "subType": {"range": ["b_customer"]},
  "itemName": "customerId",
  "itemLabel": "委托单位",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "customer",
  "subType": {"range": ["b_customer"]},
  "itemName": "clientId",
  "itemLabel": "客户",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "customer",
  "itemName": "bookingAgentId",
  "subType": {"range": ["b_booking_agent"]},
  "itemLabel": "订舱代理",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "customer",
  "subType": {"range": ["b_destination_agent"]},
  "itemName": "destinationAgentId",
  "itemLabel": "目的港代理",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "customer",
  "subType": {"range": ["b_nominated_agent"]},
  "itemName": "nominatedAgentId",
  "itemLabel": "指定货代理",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "carrier",
  "itemName": "carrierCode",
  "itemLabel": "船公司",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "customer",
  "subType": {"range": ["b_trucks"]},
  "itemName": "truckId",
  "itemLabel": "车队",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "customer",
  "subType": {"range": ["b_warehouse"]},
  "itemName": "warehouseId",
  "itemLabel": "仓库",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "jobNo",
  "itemLabel": "工作号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "input",
  "itemName": "mblNo",
  "itemLabel": "MB/L编号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "input",
  "itemName": "hblNo",
  "itemLabel": "HB/L编号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "input",
  "itemName": "soNo",
  "itemLabel": "关单号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "input",
  "itemName": "customerJobNo",
  "itemLabel": "客户参考号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "bookingNo",
  "itemLabel": "订舱编号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "customerContractNo",
  "itemLabel": "客户协议号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "bookingContractNo",
  "itemLabel": "船东约号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "warehouseNo",
  "itemLabel": "进仓编号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "vessel",
  "itemLabel": "船名",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "input",
  "itemName": "voyage",
  "itemLabel": "航次",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "port",
  "itemName": "polCode",
  "itemLabel": "起运港/POL",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "port",
  "itemName": "podCode",
  "itemLabel": "卸货港/POD",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "port",
  "itemName": "destinationCode",
  "itemLabel": "目的港",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "input",
  "itemName": "delivery",
  "itemLabel": "最终目的地",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "seaLineCode",
  "itemLabel": "航线",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "containerNo",
  "itemLabel": "箱号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "user",
  "itemName": "saleById",
  "itemLabel": "销售人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "user",
  "itemName": "opById",
  "itemLabel": "操作人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 1
}, {
  "itemType": "user",
  "itemName": "docById",
  "itemLabel": "单证人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "user",
  "itemName": "csById",
  "itemLabel": "客服人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "busById",
  "itemLabel": "商务人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "user",
  "itemName": "osById",
  "itemLabel": "海外人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "user",
  "itemName": "createBy",
  "itemLabel": "创建人员",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "select",
  "itemName": "jobState",
  "itemLabel": "工作号状态",
  "itemValue": 1,
  "selected": 0,
  "valueExpression": {
    "valueType": "static",
    "valueContent": [{"label": "未提交", "value": 0}, {"label": "待审核", "value": 1}, {
      "label": "已驳回",
      "value": 2
    }, {"label": "已审核", "value": 3}, {"label": "已完成", "value": 4}]
  },
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "businessGategory",
  "itemLabel": "业务分类",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "select",
  "multiple": 0,
  "itemName": "bCancel",
  "itemLabel": "退关(Y/N)",
  "itemValue": "",
  "selected": 0,
  "valueExpression": {"valueType": "static", "valueContent": [{"label": "是", "value": 1}, {"label": "否", "value": 0}]},
  "defaultSelected": 0
}, {
  "itemType": "office",
  "itemName": "officeId",
  "itemLabel": "所属公司",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "customerNo",
  "itemLabel": "报关单号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "select",
  "itemName": "cargoType",
  "itemLabel": "货物类型",
  "itemValue": "",
  "selected": 0,
  "valueExpression": {
    "valueType": "static",
    "valueContent": [{"label": "普货", "value": 0}, {"label": "危险品", "value": 1}, {
      "label": "冷藏品",
      "value": 2
    }, {"label": "超标货", "value": 3}, {"label": "挂衣", "value": 4}]
  },
  "defaultSelected": 0
}, {
  "itemType": "select",
  "itemName": "fclLcl",
  "itemLabel": "整拼类型",
  "itemValue": "",
  "selected": 0,
  "valueExpression": {
    "valueType": "static",
    "valueContent": [{"label": "整箱(FCL)", "value": 1}, {"label": "货代自拼(Consol)", "value": 2}, {
      "label": "货代自拼小票(LCL)",
      "value": 3
    }, {"label": "货代自拼主票(B/C)", "value": 4}, {"label": "货代自拼小票(B/C)", "value": 5}, {
      "label": "委托外拼(Co-load)",
      "value": 6
    }, {"label": "散杂货(Bulk)", "value": 7}]
  },
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "saleMode",
  "itemLabel": "揽货方式",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "masterJobNo",
  "itemLabel": "主票工作号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "billNo",
  "itemLabel": "账单号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "invoiceNo",
  "itemLabel": "发票号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "statementNo",
  "itemLabel": "对账单号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}, {
  "itemType": "input",
  "itemName": "applyNo",
  "itemLabel": "收付申请号",
  "itemValue": "",
  "selected": 0,
  "valueExpression": "",
  "defaultSelected": 0
}]

export default searchData
