export default {
  defaultFlag: true,
  moduleName: '应收账单',
  moduleCode: 'RECEIVE_BILL_PAGE',
  schemeName: '默认表头',
  schemeContent: [{
    field: 'index',
    headerNameKey: '',
    width: 55,
    pinned: 'left',
    suppressSorting: true,
    checkboxSelection: true,
    suppressMenu: true,
    suppressSizeToFit: true,
    suppressResize: true,
    headerCheckboxSelection: true
  }, {
    field: "billNo",
    headerNameKey: "uexpressFmsBill.bill_no",
    width: 130,
    hide: false
  }, {
    field: "memberName",
    headerNameKey: "uexpressFmsBill.customer_name",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "childBusinessTypeName",
    headerNameKey: "uexpressFmsBill.productType",
    width: 120,
    hide: false,
    resizable: true
  }, {
    field: "settlementCompanyName",
    headerNameKey: "uexpressFmsBill.settlement_company_name",
    width: 130,
    hide: false,
    resizable: true
  }, {
    field: "settlementOfficeName",
    headerNameKey: "uexpressFmsBill.settlement_office_name",
    width: 130,
    hide: false,
    resizable: true
  }, {
    field: "settlementModeName",
    headerNameKey: "uexpressFmsBill.settlement_mode",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "periodName",
    headerNameKey: "uexpressFmsBill.period",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "salesName",
    headerNameKey: "uexpressFmsBill.sales_names",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "billAmount",
    headerNameKey: "uexpressFmsBill.billAmount", // 账单金额
    width: 100,
    type: 'numericColumn',
    hide: false,
    resizable: true
  }, {
    field: "currency",
    headerNameKey: "uexpressFmsBill.currency", // 币种
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "billDateActual",
    headerNameKey: "uexpressFmsBill.billDate", // 账单日期
    width: 150,
    hide: false,
    resizable: true
  }, {
    field: "billStateName",
    headerNameKey: "uexpressFmsBill.bill_status",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "invoiceStateName",
    headerNameKey: "uexpressFmsBill.invoice_status",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "clearStateName",
    headerNameKey: "uexpressFmsBill.clear_status",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "billFileStateName",
    headerNameKey: "uexpressFmsBill.billFileState", // 账单文件状态
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "optionBtn",
    headerNameKey: "uexpressFmsBill.operation",
    cellRendererFramework: "OptionBtnBill",
    pinned: 'right',
    width: 180,
    hide: false,
    resizable: true
  }]
}

