export default {
  defaultFlag: true,
  moduleName: '应收费用明细',
  moduleCode: 'RECEIVE_CHARGE_PAGE',
  schemeName: '默认表头',
  schemeContent: [{
    field: 'index',
    headerNameKey: '',
    width: 55,
    pinned: 'left',
    suppressSorting: true,
    checkboxSelection: true,
    suppressMenu: true,
    suppressSizeToFit: true,
    suppressResize: true,
    headerCheckboxSelection: true
  }, {
    field: "id",
    headerNameKey: "receiveFms.charge_no",
    width: 150
  }, {
    field: "entityNo",
    headerNameKey: "receiveFms.entity_no",
    width: 150
  }, {
    field: "entityTypeName",
    headerNameKey: "receiveFms.entityTypeName",
    width: 150
  }, {
    field: "extendInfo11",
    headerNameKey: 'receiveFms.business_no',
    width: 150
  }, {
    field: "extendInfo12",
    headerNameKey: 'receiveFms.SO',
    width: 150
  }, {
    field: "extendInfo13",
    headerNameKey: 'receiveFms.MBL',
    width: 120
  }, {
    field: "extendInfo14",
    headerNameKey: 'receiveFms.HBL',
    width: 120
  }, {
    field: "invoiceNo",
    headerNameKey: 'receiveFms.invoiceNo',
    width: 120
  }, {
    field: "confirmationNo",
    headerNameKey: "receiveFms.confirmation_no",
    width: 140
  }, {
    field: "billNo",
    headerNameKey: "receiveFms.bill_no",
    width: 140
  }, {
    field: "channelOrderNo",
    headerNameKey: "receiveFms.channelOrderNo",
    width: 140
  }, {
    field: "businessTypeName",
    headerNameKey: "receiveFms.business_type",
    width: 100
  }, {
    field: "memberName",
    headerNameKey: "receiveFms.memberLocalName",
    width: 130
  }, {
    field: "settlementCompanyName",
    headerNameKey: "receiveFms.settlement_company_name",
    width: 130
  }, {
    field: "settlementOfficeName",
    headerNameKey: "receiveFms.settlement_office_name",
    width: 130
  }, {
    field: "responsiblePersonName",
    headerNameKey: "receiveFms.sales_names",
    width: 100
  }, {
    field: "feeItemName",
    headerNameKey: "receiveFms.charge_name",
    width: 110
  }, {
    field: "currency",
    headerNameKey: "receiveFms.currency",
    width: 80
  }, {
    field: "priceText", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.price",
    width: 80,
    type: 'numericColumn'
  }, {
    field: "chargeQuantity1",
    headerNameKey: "receiveFms.number",
    width: 80
  }, {
    field: "invoiceTaxRateName",
    headerNameKey: "receiveFms.tax_rate",
    width: 80
  }, {
    field: "taxAmountText", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.tax_amount",
    width: 80,
    type: 'numericColumn'
  }, {
    field: "excludeTaxAmountText", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.exclude_tax_amount",
    width: 100,
    type: 'numericColumn'
  }, {
    field: "entryAmountText", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.amount",
    width: 100,
    type: 'numericColumn'
  }, {
    field: "bussinessDate",
    headerNameKey: "receiveFms.business_date",
    width: 150
  }, {
    field: "entryDate",
    headerNameKey: "receiveFms.entry_date_estimate",
    width: 150
  }, {
    field: "settlementModeName",
    headerNameKey: "receiveFms.settlement_mode",
    width: 100
  }, {
    field: "periodName",
    headerNameKey: "receiveFms.profit_and_loss_period",
    width: 100
  }, {
    field: "lastInvoiceDate",
    headerNameKey: "receiveFms.invoice_date",
    width: 100
  }, {
    field: "lastClearedByName",
    headerNameKey: "receiveFms.clear_by",
    width: 100
  }, {
    field: "lastClearDate",
    headerNameKey: "receiveFms.clear_date",
    width: 150
  }, {
    field: "lastReceiptPayDate",
    headerNameKey: "receiveFms.receipt_pay_date",
    width: 150
  }, {
    field: "confirmDateActual",
    headerNameKey: "receiveFms.confirm_date_actual",
    width: 150
  }, {
    field: "hasClearedAmount", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.has_cleared_amount",
    width: 100,
    type: 'numericColumn'
  }, {
    field: "unClearedAmount", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.un_cleared_amount",
    width: 100,
    type: 'numericColumn'
  }, {
    field: "lastProfitDate",
    headerNameKey: "receiveFms.profit_date",
    width: 150
  }, {
    field: "confirmByName",
    headerNameKey: "receiveFms.submit_name",
    width: 100
  }, {
    field: "confirmTime",
    headerNameKey: "receiveFms.submit_time",
    width: 150
  }, {
    field: "standardAmountText", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.standard_amount",
    width: 180,
    type: 'numericColumn'
  }, {
    field: "clearingStandardAmountText", // js统一处理好之后进行展示
    headerNameKey: "receiveFms.un_clear_standard_amount",
    width: 160,
    type: 'numericColumn'
  }, {
    field: "checkPrincipalTypeName",
    headerNameKey: "receiveFms.check_principal_type_name",
    width: 150
  }, {
    field: "dateExtendInfo2",
    headerNameKey: "receiveFms.eta",
    width: 150
  }, {
    field: "entryStateName",
    headerNameKey: "receiveFms.bill_status",
    width: 100,
    pinned: 'right'
  }, {
    field: "invoiceApplyStateName",
    headerNameKey: "receiveFms.invoice_apply_state_name",
    width: 100,
    pinned: 'right'
  }, {
    field: "invoiceStateName",
    headerNameKey: "receiveFms.invoice_status",
    width: 100,
    pinned: 'right'
  }, {
    field: "instructionStateName",
    headerNameKey: "receiveFms.apply_clear_status",
    width: 120,
    pinned: 'right'
  }, {
    field: "clearStateName",
    headerNameKey: "receiveFms.clear_status",
    width: 100,
    cellRendererFramework: "ClearStateCell",
    pinned: 'right'
  }, {
    field: "profitStateName",
    headerNameKey: "receiveFms.profit_state",
    width: 100,
    pinned: 'right'
  }, {
    field: "customerBL",
    headerNameKey: "receiveFms.customerBL",
    width: 150
  }, {
    field: "businessTagTypeName",
    headerNameKey: "receiveFms.businessTag",
    width: 100
  }, {
    field: "optionBtn",
    headerNameKey: "receiveFms.operation",
    cellRendererFramework: "OptionBtnCharge",
    pinned: 'right',
    width: 80
  }]
}

