export default {
  defaultFlag: true,
  moduleName: '应收账单',
  moduleCode: 'RECEIVE_BILL_PAGE',
  schemeName: '默认表头',
  schemeContent: [{
    field: 'index',
    headerNameKey: '',
    width: 55,
    pinned: 'left',
    suppressSorting: true,
    checkboxSelection: true,
    suppressMenu: true,
    suppressSizeToFit: true,
    suppressResize: true,
    headerCheckboxSelection: true
  }, {
    field: "billNo",
    headerNameKey: "receiveFms.bill_no",
    width: 130,
    hide: false
  }, {
    field: "businessTypeName",
    headerNameKey: "receiveFms.business_type",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "settlementCompanyName",
    headerNameKey: "receiveFms.settlement_company_name",
    width: 130,
    hide: false,
    resizable: true
  }, {
    field: "settlementOfficeName",
    headerNameKey: "receiveFms.settlement_office_name",
    width: 130,
    hide: false,
    resizable: true
  }, {
    field: "periodName",
    headerNameKey: "receiveFms.period",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "settlementModeName",
    headerNameKey: "receiveFms.settlement_mode",
    width: 100
  }, {
    field: "entityTypeName",
    headerNameKey: "receiveFms.entityTypeName",
    width: 150
  }, {
    field: "salesName",
    headerNameKey: "receiveFms.sales_names",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "USD",
    headerNameKey: "common.USD",
    width: 100,
    type: 'numericColumn',
    hide: false,
    resizable: true
  }, {
    field: "CNY",
    headerNameKey: "common.CNY",
    width: 100,
    type: 'numericColumn',
    hide: false,
    resizable: true
  }, {
    field: "EUR",
    headerNameKey: "common.EUR",
    width: 100,
    type: 'numericColumn',
    hide: false,
    resizable: true
  }, {
    field: "GBP",
    headerNameKey: "common.GBP",
    width: 100,
    type: 'numericColumn',
    hide: false,
    resizable: true
  }, {
    field: "HKD",
    headerNameKey: "common.HKD",
    width: 100,
    type: 'numericColumn',
    hide: false,
    resizable: true
  }, {
    field: "billDateEstimate",
    headerNameKey: "receiveFms.bill_date_estimate",
    width: 150,
    hide: false,
    resizable: true
  }, {
    field: "billDateActual",
    headerNameKey: "receiveFms.bill_date_actual",
    width: 150,
    hide: false,
    resizable: true
  }, {
    field: "confirmDateEstimate",
    headerNameKey: "receiveFms.confirm_date_estimate",
    width: 150,
    hide: false,
    resizable: true
  }, {
    field: "confirmDateActual",
    headerNameKey: "receiveFms.confirm_date_actual",
    width: 150,
    hide: false,
    resizable: true
  }, {
    field: "billStateName",
    headerNameKey: "receiveFms.bill_status",
    width: 100,
    hide: false,
    resizable: true,
    cellRendererFramework: 'BillState'
  }, {
    field: "invoiceApplyStateName",
    headerNameKey: "receiveFms.invoice_apply_state_name",
    width: 100
  }, {
    field: "invoiceStateName",
    headerNameKey: "receiveFms.invoice_status",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "instructionStateName",
    headerNameKey: "receiveFms.apply_clear_status",
    width: 120,
    hide: false,
    resizable: true
  }, {
    field: "clearStateName",
    headerNameKey: "receiveFms.clear_status",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "pushEmailStateName",
    headerNameKey: "receiveFms.pushEmailStateName",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "pushEmailResultMsg",
    headerNameKey: "receiveFms.pushEmailResultMsg",
    width: 120,
    hide: false,
    resizable: true
  }, {
    field: "confirmByName",
    headerNameKey: "receiveFms.confirm_by_name",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "createByName",
    headerNameKey: "receiveFms.create_by_name",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "billFileStateName",
    headerNameKey: "receiveFms.billFileStateName",
    width: 100,
    hide: false,
    resizable: true
  }, {
    field: "JPY",
    headerNameKey: "common.JPY",
    width: 100,
    type: 'numericColumn',
    hide: true,
    resizable: true
  },
  {
    field: "AUD",
    headerNameKey: "common.AUD",
    width: 100,
    type: 'numericColumn',
    hide: true,
    resizable: true
  },
  {
    field: "BRL",
    headerNameKey: "common.BRL",
    width: 100,
    type: 'numericColumn',
    hide: true,
    resizable: true
  },
  {
    field: "MAN",
    headerNameKey: "common.MAN",
    width: 100,
    type: 'numericColumn',
    hide: true,
    resizable: true
  },
  {
    field: "VND",
    headerNameKey: "common.VND",
    width: 100,
    type: 'numericColumn',
    hide: true,
    resizable: true
  }, {
    field: "optionBtn",
    headerNameKey: "receiveFms.operation",
    cellRendererFramework: "OptionBtnBill",
    pinned: 'right',
    width: 220,
    hide: false,
    resizable: true
  }]
}

